<?php

namespace ContainerAYboa3W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageFormTypeService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private 'App\Form\MessageFormType' shared autowired service.
     *
     * @return \App\Form\MessageFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MessageFormType.php';

        return $container->privates['App\\Form\\MessageFormType'] = new \App\Form\MessageFormType();
    }
}
