<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAYboa3W\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAYboa3W/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerAYboa3W.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerAYboa3W\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerAYboa3W\App_KernelProdDebugContainer([
    'container.build_hash' => 'AYboa3W',
    'container.build_id' => '58995fc3',
    'container.build_time' => 1728400331,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAYboa3W');
