<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIPFnTlV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIPFnTlV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIPFnTlV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIPFnTlV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIPFnTlV\App_KernelDevDebugContainer([
    'container.build_hash' => 'IPFnTlV',
    'container.build_id' => 'abdc3bc4',
    'container.build_time' => 1728233594,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIPFnTlV');
